version: "3.8"

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: empresta-ae-db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empresta_ae
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - empresta-ae-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: empresta-ae-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - empresta-ae-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./backend
      target: dev
    container_name: empresta-ae-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: empresta_ae
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-at-least-32-characters-long-for-development
      REFRESH_TOKEN_SECRET: your-super-secret-refresh-token-key-at-least-32-characters-long-for-development
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    networks:
      - empresta-ae-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      timeout: 20s
      retries: 10

  # Frontend
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: empresta-ae-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - empresta-ae-network
    depends_on:
      - backend

  # Test Database (for running tests)
  db_test:
    image: mysql:8.0
    container_name: empresta-ae-db-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empresta_ae_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - empresta-ae-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Test Redis
  redis_test:
    image: redis:7-alpine
    container_name: empresta-ae-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - empresta-ae-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  mysql_test_data:
  redis_data:
  redis_test_data:
  backend_uploads:

networks:
  empresta-ae-network:
    driver: bridge
